esphome:
  name: heater-control
  friendly_name: Heater-Control
  includes:
    - cdh.h

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heater-Control Fallback Hotspot"
    password: "HWhtQEgq0YA8"

captive_portal:
    
web_server:
  port: 80


#Establish SPI comms
spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

cc1101:
  id: "radio"
  #General Settings
  cs_pin: GPIO5
  gdo0_pin: GPIO32
  frequency: 433.955MHz
  modulation_type:  GFSK
  symbol_rate:  10000   #10k baud
  #Tuner Settings
  #filter_bandwidth: 58kHz    #Got better signals commented out
  #fsk_deviation:  11.1kHz
  fsk_deviation:  12kHz
  #Packet Mode Settings
  packet_mode:  True
  packet_length:  0    #Come back to this for more packets from remote
  #Changing to variable packet length cuts off leading byte of packet as reported length
    #as used in cc1101, Also cuts off trailing 2 bytes used to report packet info from cc1101
  #packet_length:  26
  crc_enable: True   #Should be true
  sync_mode:  30/32
  sync0:  0x3C
  sync1:  0x7E
  #AGC Settings
  max_dvga_gain:  Default
  carrier_sense_abs_thr:  0
  #Actions
  on_packet:
    then:
      # - logger.log: "Packet Recieved"
      - lambda: |-
          read_packet(x.data());

#Wake up heater and get current conditions
interval:
  - interval: 6 sec
    then:
      - lambda: |-
          tx_packet(0x23);
      #- logger.log: "Transmitted packet"
  - interval: 10 sec
    then:
      #- logger.log: "State Loop Triggered"
      - lambda: |-
          state_loop();

sensor:
  - platform: number
    name: "Supply Voltage"
    source_id: nullI
    id: voltageI
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 1
  - platform: number
    name: "Water Temperature"
    id: waterTempI
    source_id: nullI
    device_class: "temperature"
    state_class: "measurement"
    icon: "mdi:thermometer-water"
  - platform: number
    name: "Ambient Temperature"
    id: ambientTempI
    source_id: nullI
    device_class: "temperature"
    state_class: "measurement"
    icon: "mdi:thermometer"
  - platform: number
    name: "pumpFrequency"
    id: pumpFrequencyI
    source_id: nullI
    device_class: "frequency"
    state_class: "measurement"
    icon: "mdi:pump"
    accuracy_decimals: 1
  - platform: number
    name: "Setpoint"
    id: setPointI
    source_id: nullI
    #device_class: "temperature"
    state_class: "measurement"
    icon: "mdi:speedometer"
  - platform: number
    name: "Ex Temp maybe"
    id: byteF
    source_id: nullI
    device_class: "temperature"
    state_class: "measurement"
    icon: "mdi:thermometer"

number:
  - platform: template
    id: "nullI"
    step: 0.1
    min_value: 0
    max_value: 9
    optimistic: true

text_sensor:
  - platform: template
    id: "stateI"
    name: "HeaterState"
  - platform: template
    id: "autoI"
    name: "Auto Mode"
  - platform: template
    id: "byteA"
    name: "Unknown Byte 7"
  - platform: template
    id: "byteB"
    name: "Unknown Byte 10"
  - platform: template
    id: "byteC"
    name: "Unknown Byte 13"
  - platform: template
    id: "byteD"
    name: "Unknown Byte 16"
  - platform: template
    id: "byteE"
    name: "Unknown Byte 17"
  # - platform: template
  #   id: "byteF"
  #   name: "Unknown Byte 18"

button:
  - platform: template
    id: onoffI
    name: "Heater On Off"
    on_press:
      then:
        - lambda: |-
            tx_packet(0x2B);
            ESP_LOGD("cdh", "On Off cycled");
  - platform: template
    id: upI
    name: "Heater Up"
    on_press:
      then:
        - lambda: |-
            tx_packet(0x3C);
            ESP_LOGD("cdh", "Up called");
  - platform: template
    id: downI
    name: "Heater Down"
    on_press:
      then:
        - lambda: |-
            tx_packet(0x3E);
            ESP_LOGD("cdh", "Down called");

switch:
  - platform: template
    id: onoffSW
    name: "PowerSW"
    icon: "mdi:PowerCycle"
    optimistic: True
  - platform: template
    id: powerI
    name: "Power"
    optimistic: True
    internal: True